# -*- coding: utf-8 -*-
"""Adivina mi numero.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XmoM8w988rYS1EVuMnKfY9G7yo2buG7x
"""

from random import random
x=int(100*random())
print('Adivina un numero del 0 al 100\n')
ni= 1 #Variable contadora de numero de intentos
# inicia declaración de control iterativo
flag=True # =NO ADIVINÓ. Cuando <<buscamos>> algo podemo usar un flag

while flag :
  y=int(input('Escribe tu numero: '))
  if x==y:
    print('Felicitaciones. Adivinaste ',x)
    print('Numero de intentos totales',ni)
    flag=False
    break

  if x>y:
    print('Debes aumentar la apuesta')
    ni=ni+1
  if x<y:
    print('Debes disminuir la apuesta')
    ni=ni+1